"use strict";
/**
 * This file was generated by mrapi
 * Do not make changes to this file directly
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.UserFindManyQuery = void 0;
const schema_1 = require("@nexus/schema");
exports.UserFindManyQuery = schema_1.queryField('findManyUser', {
    type: 'User',
    nullable: true,
    list: true,
    args: {
        where: 'UserWhereInput',
        orderBy: schema_1.arg({ type: 'UserOrderByInput', list: true }),
        cursor: 'UserWhereUniqueInput',
        skip: 'Int',
        take: 'Int',
        select: 'UserSelect',
    },
    resolve(_parent, args, { prisma }) {
        return prisma.user.findMany(args);
    },
});
