"use strict";
/**
 * This file was generated by mrapi
 * Do not make changes to this file directly
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.UserFindOneQuery = void 0;
const schema_1 = require("@nexus/schema");
exports.UserFindOneQuery = schema_1.queryField('findOneUser', {
    type: 'User',
    nullable: true,
    args: {
        where: schema_1.arg({
            type: 'UserWhereUniqueInput',
            nullable: false,
        }),
        select: 'UserSelect',
    },
    resolve(_parent, args, { prisma }) {
        return prisma.user.findOne(args);
    },
});
