"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.User = void 0;
/**
 * This file was generated by mrapi
 * Do not make changes to this file directly
 */
const schema_1 = require("@nexus/schema");
exports.User = schema_1.objectType({
    name: 'User',
    definition(t) {
        t.string('email', { nullable: false });
        t.int('id', { nullable: false });
        t.string('name', { nullable: true });
        t.field('Post', {
            nullable: false,
            list: [true],
            type: 'Post',
            args: {
                where: 'PostWhereInput',
                orderBy: 'PostOrderByInput',
                cursor: 'PostWhereUniqueInput',
                take: 'Int',
                skip: 'Int',
                distinct: 'PostDistinctFieldEnum',
            },
            resolve(parent) {
                return parent['Post'];
            },
        });
    },
});
