/**
 * This file was generated by mrapi
 * Do not make changes to this file directly
 */
import { objectType } from '@nexus/schema'

export const User = objectType({
  name: 'User',
  definition(t) {
    t.string('email', { nullable: false })
    t.int('id', { nullable: false })
    t.string('name', { nullable: true })
    t.field('Post', {
      nullable: false,
      list: [true],
      type: 'Post',
      args: {
        where: 'PostWhereInput',
        orderBy: 'PostOrderByInput',
        cursor: 'PostWhereUniqueInput',
        take: 'Int',
        skip: 'Int',
        distinct: 'PostDistinctFieldEnum',
      },
      resolve(parent: any) {
        return parent['Post']
      },
    })
  },
})
