/**
 * This file was generated by mrapi
 * Do not make changes to this file directly
 */

import { queryField, arg } from '@nexus/schema'

export const PostAggregateQuery = queryField('aggregatePost', {
  type: 'AggregatePost',
  nullable: true,
  args: {
    where: 'PostWhereInput',
    orderBy: arg({ type: 'PostOrderByInput', list: true }),
    cursor: 'PostWhereUniqueInput',
    skip: 'Int',
    take: 'Int',
  },
  resolve(_parent, args, { prisma }) {
    return prisma.post.aggregate(args) as any
  },
})
