"use strict";
/**
 * This file was generated by mrapi
 * Do not make changes to this file directly
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.PostFindOneQuery = void 0;
const schema_1 = require("@nexus/schema");
exports.PostFindOneQuery = schema_1.queryField('findOnePost', {
    type: 'Post',
    nullable: true,
    args: {
        where: schema_1.arg({
            type: 'PostWhereUniqueInput',
            nullable: false,
        }),
        select: 'PostSelect',
        include: 'PostInclude',
    },
    resolve(_parent, args, { prisma }) {
        return prisma.post.findOne(args);
    },
});
