/**
 * This file was generated by mrapi
 * Do not make changes to this file directly
 */

import { queryField, arg } from '@nexus/schema'

export const PostFindOneQuery = queryField('findOnePost', {
  type: 'Post',
  nullable: true,
  args: {
    where: arg({
      type: 'PostWhereUniqueInput',
      nullable: false,
    }),
    select: 'PostSelect',
    include: 'PostInclude',
  },
  resolve(_parent, args, { prisma }) {
    return prisma.post.findOne(args) as any
  },
})
