/**
 * This file was generated by mrapi
 * Do not make changes to this file directly
 */

import { queryField, arg } from '@nexus/schema'

export const PostFindManyQuery = queryField('findManyPost', {
  type: 'Post',
  nullable: true,
  list: true,
  args: {
    where: 'PostWhereInput',
    orderBy: arg({ type: 'PostOrderByInput', list: true }),
    cursor: 'PostWhereUniqueInput',
    skip: 'Int',
    take: 'Int',
    select: 'PostSelect',
    include: 'PostInclude',
  },
  resolve(_parent, args, { prisma }) {
    return prisma.post.findMany(args) as any
  },
})
