"use strict";
/**
 * This file was generated by mrapi
 * Do not make changes to this file directly
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.PostFindManyQuery = void 0;
const schema_1 = require("@nexus/schema");
exports.PostFindManyQuery = schema_1.queryField('findManyPost', {
    type: 'Post',
    nullable: true,
    list: true,
    args: {
        where: 'PostWhereInput',
        orderBy: schema_1.arg({ type: 'PostOrderByInput', list: true }),
        cursor: 'PostWhereUniqueInput',
        skip: 'Int',
        take: 'Int',
        select: 'PostSelect',
        include: 'PostInclude',
    },
    resolve(_parent, args, { prisma }) {
        return prisma.post.findMany(args);
    },
});
