"use strict";
/**
 * This file was generated by mrapi
 * Do not make changes to this file directly
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.PostFindManyCountQuery = void 0;
const schema_1 = require("@nexus/schema");
exports.PostFindManyCountQuery = schema_1.queryField('findManyPostCount', {
    type: 'Int',
    args: {
        where: 'PostWhereInput',
        orderBy: schema_1.arg({ type: 'PostOrderByInput', list: true }),
        cursor: 'PostWhereUniqueInput',
        skip: 'Int',
        take: 'Int',
    },
    resolve(_parent, args, { prisma }) {
        return prisma.post.count(args);
    },
});
