/**
 * This file was generated by mrapi
 * Do not make changes to this file directly
 */
exports.default = {
  Error: {
    type: 'object',
    properties: {
      code: { description: 'Error code.', type: 'integer' },
      message: { description: 'Error message.', type: 'string' },
    },
  },
  User: {
    type: 'object',
    properties: {
      email: { description: 'email', type: 'string' },
      id: { description: 'id', type: 'integer' },
      name: { description: 'name', type: 'string' },
    },
    required: ['email', 'id'],
  },
  UserCreateInput: {
    type: 'object',
    properties: {
      email: { description: 'email', type: 'string' },
      name: { description: 'name', type: 'string' },
    },
    required: ['email'],
  },
}
