/**
 * This file was generated by mrapi
 * Do not make changes to this file directly
 */
import { objectType } from '@nexus/schema'

export const Post = objectType({
  name: 'Post',
  definition(t) {
    t.int('authorId', { nullable: true })
    t.string('content', { nullable: true })
    t.int('id', { nullable: false })
    t.boolean('published', { nullable: false })
    t.string('title', { nullable: false })
    t.field('User', {
      nullable: true,
      type: 'User',
      resolve(parent: any) {
        return parent['User']
      },
    })
  },
})
