"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Post = void 0;
/**
 * This file was generated by mrapi
 * Do not make changes to this file directly
 */
const schema_1 = require("@nexus/schema");
exports.Post = schema_1.objectType({
    name: 'Post',
    definition(t) {
        t.int('authorId', { nullable: true });
        t.string('content', { nullable: true });
        t.int('id', { nullable: false });
        t.boolean('published', { nullable: false });
        t.string('title', { nullable: false });
        t.field('User', {
            nullable: true,
            type: 'User',
            resolve(parent) {
                return parent['User'];
            },
        });
    },
});
