/**
 * This file was generated by mrapi
 * Do not make changes to this file directly
 */

import { queryField, arg } from '@nexus/schema'

export const UserFindOneQuery = queryField('findOneUser', {
  type: 'User',
  nullable: true,
  args: {
    where: arg({
      type: 'UserWhereUniqueInput',
      nullable: false,
    }),
    select: 'UserSelect',
    include: 'UserInclude',
  },
  resolve(_parent, args, { prisma }) {
    return prisma.user.findOne(args) as any
  },
})
