/**
 * This file was generated by mrapi
 * Do not make changes to this file directly
 */

import { queryField, arg } from '@nexus/schema'

export const UserFindManyQuery = queryField('findManyUser', {
  type: 'User',
  nullable: true,
  list: true,
  args: {
    where: 'UserWhereInput',
    orderBy: arg({ type: 'UserOrderByInput', list: true }),
    cursor: 'UserWhereUniqueInput',
    skip: 'Int',
    take: 'Int',
    select: 'UserSelect',
    include: 'UserInclude',
  },
  resolve(_parent, args, { prisma }) {
    return prisma.user.findMany(args) as any
  },
})
