"use strict";
/**
 * This file was generated by mrapi
 * Do not make changes to this file directly
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.UserFindManyCountQuery = void 0;
const schema_1 = require("@nexus/schema");
exports.UserFindManyCountQuery = schema_1.queryField('findManyUserCount', {
    type: 'Int',
    args: {
        where: 'UserWhereInput',
        orderBy: schema_1.arg({ type: 'UserOrderByInput', list: true }),
        cursor: 'UserWhereUniqueInput',
        skip: 'Int',
        take: 'Int',
    },
    resolve(_parent, args, { prisma }) {
        return prisma.user.count(args);
    },
});
