/**
 * This file was generated by mrapi
 * Do not make changes to this file directly
 */
exports.default = {
  Error: {
    type: 'object',
    properties: {
      code: { description: 'Error code.', type: 'integer' },
      message: { description: 'Error message.', type: 'string' },
    },
  },
  User: {
    type: 'object',
    properties: {
      email: { description: 'email', type: 'string' },
      id: { description: 'id', type: 'integer' },
      name: { description: 'name', type: 'string' },
    },
    required: ['email', 'id'],
  },
  UserCreateInput: {
    type: 'object',
    properties: {
      email: { description: 'email', type: 'string' },
      name: { description: 'name', type: 'string' },
    },
    required: ['email'],
  },
  Post: {
    type: 'object',
    properties: {
      authorId: { description: 'authorId', type: 'integer' },
      content: { description: 'content', type: 'string' },
      id: { description: 'id', type: 'integer' },
      published: { description: 'published', type: 'boolean' },
      title: { description: 'title', type: 'string' },
    },
    required: ['id', 'published', 'title'],
  },
  PostCreateInput: {
    type: 'object',
    properties: {
      content: { description: 'content', type: 'string' },
      published: { description: 'published', type: 'boolean' },
      title: { description: 'title', type: 'string' },
    },
    required: ['title'],
  },
}
